/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

long factorial(int n)
{
	if (n == 0)
		return 1;
	else
	return(n *factorial(n-1));
}

int *
add_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result;
	int fact;

	/*
	 * insert server code here
	 */
	// printf("add function\n");
	printf("parameters: %d\n",argp->a);
	result = factorial(argp->a);
	// result = argp->a + argp->a;
	printf("Factorial of %d is : %d\n", argp->a,result);

	return &result;
}
