/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intstr.h"
#include <stdio.h>

void
intstr_prog_1(char *host, int i)
{
	CLIENT *clnt;
	char * *result_1;
	intstring  intstr_1_arg;


#ifndef	DEBUG
	clnt = clnt_create (host, INTSTR_PROG, INTSTR_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	intstr_1_arg.i = i;

	result_1 = intstr_1(&intstr_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int i;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	if (argc > 3)
	{
		i = atoi(argv[3]);

		if (i < 0 || i > 100)
		{
			printf("Invalid integer: %d", i);
			exit(1);
		}
	}
	intstr_prog_1 (host,i);
exit (0);
}
