/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "intstr.h"

bool_t
xdr_intstring (XDR *xdrs, intstring *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	return TRUE;
}
