/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intstr.h"

char **
intstr_1_svc(intstring *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("the interger is, %d\n",argp->i);
	/*
	 * insert server code here
	 */
	result = (char *)malloc(100);
	printf("G%dd Friday\n",argp->i);
	// result = "Halima";

	return &result;
}
