/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _INTSTR_H_RPCGEN
#define _INTSTR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct intstring {
	int i;
};
typedef struct intstring intstring;

#define INTSTR_PROG 0x19101925
#define INTSTR_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define INTSTR 1
extern  char ** intstr_1(intstring *, CLIENT *);
extern  char ** intstr_1_svc(intstring *, struct svc_req *);
extern int intstr_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INTSTR 1
extern  char ** intstr_1();
extern  char ** intstr_1_svc();
extern int intstr_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_intstring (XDR *, intstring*);

#else /* K&R C */
extern bool_t xdr_intstring ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_INTSTR_H_RPCGEN */
