/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "intstring.h"

bool_t
xdr_intstring (XDR *xdrs, intstring *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->i))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->s, 16))
		 return FALSE;
	return TRUE;
}
