/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intstring.h"


void
stint_prog_1(char *host, char *s, int i)
{
	CLIENT *clnt;
	float  *result_1;
	intstring  stint_str_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, STINT_PROG, STINT_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	stint_str_1_arg.s = s;
	stint_str_1_arg.i = i;

	result_1 = stint_str_1(&stint_str_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("Result: %f", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *s;
	int i;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if (argc > 2)
	{
		s = argv[2];
		for (i = 0; i < strlen(s); i++)
		{
			if (!isalpha(s[i]))
			{
				printf("Invalid string: %s", s);
				exit(1);
			}
		}
	}

	if (argc > 3)
	{
		i = atoi(argv[3]);
		if (i < 0 || i > 100)
		{
			printf("Invalid integer: %d", i);
			exit(1);
		}
	}
	stint_prog_1 (host,s,i);
exit (0);
}
