/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "intstring.h"

float *
stint_str_1_svc(intstring *argp, struct svc_req *rqstp)
{
	static float  result;
	// int i = argp->i;
	
	printf("%d",argp->i);
	result = (float)argp->i * strlen(argp->s);
	/*
	 * insert server code here
	 */

	return &result;
}
